### ISSUE TITLE
Allow background-image to be set per page in an dashboard app

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2325]
### Summary of the new feature / enhancement

As a developer, I want to be able to change the background so that i can change the the look and feel of my website without hacking the DOM. 

### Proposed technical implementation details (optional)

This example is from my angular website:
![image](https://user-images.githubusercontent.com/1987296/232892887-301edb7c-5508-4e95-a432-b1c59da7a0dd.png)

example:
```html
<div id="my-background" class="my-background" style="background-image: url(&quot;assets/images/Customers.jpg&quot;);">
	<div id="my-background-mask" class="my-background-mask"/>
</div>
```

```css
.my-background {
    background-position: 50%;
    background-repeat: no-repeat;
    background-size: cover;
    overflow: hidden;
    position: fixed;
    top: 0;
    bottom: 0;
    right: 0;
    z-index: -2;
    left: 0;
    margin-left: 0;
    transition-delay: .2s;
    transition: transform .2s cubic-bezier(0,.9,.1,1),margin .2s cubic-bezier(0,.9,.1,1);
}

.my-background-mask {
    background-color: rgba(102,102,102,0.62);
}

.my-background-mask {
    width: 100%;
    height: 100%;
    min-height: 100%;
    position: fixed;
    left: 0;
    top: 0;
    z-index: -1;
}
```
