### ISSUE TITLE
4.1.6 - Invalid configuration: authentication.ps1

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2764]
### Version

4.1.5

### Severity

High

### Steps to Reproduce

Just upgraded my test docker containers from 4.1.4 to 4.1.6, and now none of the Apps / Dashboards can start.
If i "downgrade" from 4.1.6 to 4.1.5 it works as expected.

This error is shown once i try to start the Apps / Dashboards.
![image](https://github.com/ironmansoftware/issues/assets/53445047/809313bc-0e5e-4f12-8ee3-8dfbe754143b)

Dashboard 1; Request failed with status code 500

Docker compose file:
```
version: "3.7"
services:
  PSU:
    container_name: PSUTest01
    image: ironmansoftware/universal:latest
    ports:
      - 80:5000
    restart: unless-stopped
    network_mode: bridge
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - /docker/container/psutest01:/root
```

### Expected behavior

```console
That it would work, and that authentication would work like with all other PSU releases.
```

### Actual behavior

```console
Impossible to start a Apps / Dashboard.
```
