### ISSUE TITLE
Endpoint API Documentation does not support basic types of input\output

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2935]
### Version

4.2.5

### Severity

Low

### Steps to Reproduce

Documentation like this does not work. 

```
.INPUTS 
    Required: false
    Description: This is an input value.
    Content: 
        application/json: string[]
```

### Expected behavior

```console
Use basic types of input and output
```

### Actual behavior

```console
No way to specify basic types.
```
