### ISSUE TITLE
New-UDCardMedia - Add -Sx or -Style parameter

### ISSUE THREAD

**Issue by eizedev** [ironmansoftware/powershell-universal#4145]
### Summary of the new feature / enhancement

As a developer i want to add custom styles to images using `New-UDCardMedia`.

`New-UDCard`. `New-UDCardBody` and `New-UDCardFooter` also already have a `-Style` parameter.

For example i want style the `object-fit`, `width` or `display: flex` stuff for an Image displayed in a card.

Example:

### Without Style/Sx

![image](https://github.com/user-attachments/assets/161ba191-6396-4490-ac7c-eb693927dea7)

### With Style/Sx

![image](https://github.com/user-attachments/assets/8237af6d-02e9-4b58-beae-e133447d2030)

Used css for this example: 

```css
.jss21 {
    object-fit: scale-down;
    background-color: transparent;
    width: 80%;
    display: flex;
    justify-self: center;
}
```

Currently the default is `object-fit: cover` & `background-color: transparent`

Thanks 
René
