### ISSUE TITLE
Add examples to swagger

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#4184]
### Summary of the new feature / enhancement

as a dev i want to be able to use the .EXAMPLE and have it show up in swagger.

i don't know if this is easy or not, i would hope it is easy

### Proposed technical implementation details (optional)

https://docs.powershelluniversal.com/api/openapi
https://swagger.io/docs/specification/v3_0/adding-examples/#:~:text=You%20can%20add%20examples%20to,your%20API%20in%20some%20way.

i think this is the section we are interested, but they do not have any examples of what it looks like after it is rendered.
```
text/html:
    schema:
      type: string
    examples:
      html:
        summary: A list containing two items
        value: "<html><body><ul><li>item 1</li><li>item 2</li></ul></body></html>"
```

The end result should let me put in something like this and have it displayed in swagger nicely:

```
.EXAMPLE
$body = [PSCustomObject]@{
    customerId = '1131'
    providerName = 'Bob'
    environment = "PROD"
} | convertto-json

Invoke-RestMethod https://dev.domain.com/bot/jh/statuspage/api/v1/incidents/resolve -Method POST -Body $body
```
