### ISSUE TITLE
Login Page Styling Improvements

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#4698]
### Summary of the new feature / enhancement

Previous versions of PSU had better login page styling options. We should add the following: 

- Login Page Background\Text Color
- Apply above colors to buttons
- Provide options for both dark and light colors
- Image Sizing 

For anyone looking for this with the current implementation, you can do it with CSS. Set the CSS file in branding and point it to a published folder hosting a CSS file. Use the following CSS to adjust the colors and image size. 

```css
#logo {
    width: 500px !important;
}

.ant-btn-primary {
    background-color: #a5d7d2 !important;
    border-color: #a5d7d2 !important;
    color: #000 !important;
}

.ant-layout {
    background-color: #a5d7d2 !important;
}
```
